server.port=8091
server.servlet.context-path=/app
#jsp용 뷰리졸버 설정 필요 없음
#타임리프는 resources/template/파일명.html을 기본으로 사용함
# image, js, css 설정 필요 없음, resource/static 기본으로 설정해줌 
#  images/a.jpg로 사용 
spring.messages.basename=message/greeting
spring.messages.encoding=utf-8
spring.messages.fallback-to-system-locale=false
spring.web.locale=ko_KR
#spring.web.locale=en_US
spring.web.locale-resolver=fixed







































































































































































































































































































































