spring.application.name=boot17_2_tdd_basic_web_1

#정적자원 매핑 취소
#spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true
#404에러 발생시 NoHandlerFoundException 을 throws함


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8090
server.servlet.context-path=/app

#image, css, js
spring.mvc.static-path-pattern=/resources/**

